spring.datasource.url=jdbc:postgresql://localhost:5432/routinequest
spring.datasource.username=routine_admin
spring.datasource.password=AdminRoutine
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true